In [54]:
# Install
%pip install -r requirements.txt --upgrade
%pip install wbdata

Requirement already satisfied: Pint>=0.25 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (0.25.2)
Requirement already satisfied: numpy>=2.0 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (2.4.2)
Requirement already satisfied: pandas>=2.0 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: requests>=2.32 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (2.32.5)
Requirement already satisfied: scipy>=1.17 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (1.17.1)
Requirement already satisfied: gspread in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (5.12.4)
Collecting gspread (from -r requirements.txt (line 6))
  Using cached gspread-6.2.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: gspread_pandas in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (3.3.0)
Requirement already satisfied: bottleneck>=1.6 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (1.6.0)
Requirement already satisfied: eep153_tools in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (0.12.4)
Requirement already satisfied: fooddatacentral>=1.0.11 in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (1.0.12)
Requirement already satisfied: python-gnupg in /srv/conda/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (0.5.6)
Requirement already satisfied: flexcache>=0.3 in /srv/conda/lib/python3.11/site-packages (from Pint>=0.25->-r requirements.txt (line 1)) (0.3)
Requirement already satisfied: flexparser>=0.4 in /srv/conda/lib/python3.11/site-packages (from Pint>=0.25->-r requirements.txt (line 1)) (0.4)
Requirement already satisfied: platformdirs>=2.1.0 in /srv/conda/lib/python3.11/site-packages (from Pint>=0.25->-r requirements.txt (line 1)) (4.3.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /srv/conda/lib/python3.11/site-packages (from Pint>=0.25->-r requirements.txt (line 1)) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /srv/conda/lib/python3.11/site-packages (from pandas>=2.0->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /srv/conda/lib/python3.11/site-packages (from requests>=2.32->-r requirements.txt (line 4)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/lib/python3.11/site-packages (from requests>=2.32->-r requirements.txt (line 4)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /srv/conda/lib/python3.11/site-packages (from requests>=2.32->-r requirements.txt (line 4)) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /srv/conda/lib/python3.11/site-packages (from requests>=2.32->-r requirements.txt (line 4)) (2026.2.25)
Requirement already satisfied: google-auth>=1.12.0 in /srv/conda/lib/python3.11/site-packages (from gspread->-r requirements.txt (line 6)) (2.41.1)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /srv/conda/lib/python3.11/site-packages (from gspread->-r requirements.txt (line 6)) (1.3.0)
Requirement already satisfied: decorator in /srv/conda/lib/python3.11/site-packages (from gspread_pandas->-r requirements.txt (line 7)) (5.1.1)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /srv/conda/lib/python3.11/site-packages (from google-auth>=1.12.0->gspread->-r requirements.txt (line 6)) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /srv/conda/lib/python3.11/site-packages (from google-auth>=1.12.0->gspread->-r requirements.txt (line 6)) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /srv/conda/lib/python3.11/site-packages (from google-auth>=1.12.0->gspread->-r requirements.txt (line 6)) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in /srv/conda/lib/python3.11/site-packages (from rsa<5,>=3.1.4->google-auth>=1.12.0->gspread->-r requirements.txt (line 6)) (0.6.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /srv/conda/lib/python3.11/site-packages (from google-auth-oauthlib>=0.4.1->gspread->-r requirements.txt (line 6)) (2.0.0)
Requirement already satisfied: six>=1.5 in /srv/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=2.0->-r requirements.txt (line 3)) (1.17.0)
Requirement already satisfied: oauthlib>=3.0.0 in /srv/conda/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread->-r requirements.txt (line 6)) (3.3.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: wbdata in /srv/conda/lib/python3.11/site-packages (1.1.0)
Requirement already satisfied: appdirs<2,>=1.4 in /srv/conda/lib/python3.11/site-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff<3,>=2.2.1 in /srv/conda/lib/python3.11/site-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools<6,>=5.3.2 in /srv/conda/lib/python3.11/site-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser<2,>=1.2.0 in /srv/conda/lib/python3.11/site-packages (from wbdata) (1.3.0)
Requirement already satisfied: decorator<6,>=5.1.1 in /srv/conda/lib/python3.11/site-packages (from wbdata) (5.1.1)
Requirement already satisfied: requests<3,>=2.0 in /srv/conda/lib/python3.11/site-packages (from wbdata) (2.32.5)
Requirement already satisfied: shelved-cache<0.4,>=0.3.1 in /srv/conda/lib/python3.11/site-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate<1,>=0.8.5 in /srv/conda/lib/python3.11/site-packages (from wbdata) (0.10.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /srv/conda/lib/python3.11/site-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /srv/conda/lib/python3.11/site-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /srv/conda/lib/python3.11/site-packages (from dateparser<2,>=1.2.0->wbdata) (2026.2.28)
Requirement already satisfied: tzlocal>=0.2 in /srv/conda/lib/python3.11/site-packages (from dateparser<2,>=1.2.0->wbdata) (5.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /srv/conda/lib/python3.11/site-packages (from requests<3,>=2.0->wbdata) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/lib/python3.11/site-packages (from requests<3,>=2.0->wbdata) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /srv/conda/lib/python3.11/site-packages (from requests<3,>=2.0->wbdata) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /srv/conda/lib/python3.11/site-packages (from requests<3,>=2.0->wbdata) (2026.2.25)
Requirement already satisfied: six>=1.5 in /srv/conda/lib/python3.11/site-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [55]:
# Import 
import fooddatacentral as fdc
import pandas as pd
import numpy as np
from datascience import *
from scipy.optimize import linprog
import wbdata
import warnings 

apikey = "hhXDThEWfQoAua41aVdG81iaAHEhLCC0An6FqziG"
warnings.filterwarnings('ignore')

In [56]:
# [A] Dietary Reference Intake

# Reading Table
df_min = Table.read_table('Dietary Requirements - diet_minimums.csv')
df_max = Table.read_table('Dietary Requirements - diet_maximums.csv')

#Sex: Type F or M
def dri(age, sex):
    if age <= 3:
        sex = 'C'
        age_t = '1-3'
    elif 4 <= age <= 8:
        age_t = '4-8'
    elif 9 <= age <= 13:
        age_t = '9-13'
    elif 14 <= age <= 18:
        age_t = '14-18'
    elif 19 <= age <= 30:
        age_t = '19-30'
    elif 31 <= age <= 50:
        age_t = '31-50'
    else:
        age_t = '51+'

    column = sex + " " + age_t

    # Some nutrients does not have a maximum so it should be infinite
    # Using 999999 because later linprog function does not allow float('Inf')
    # But 999999 would be fair as it is a really big number
    data = {
            'Nutrition': np.insert(df_min.column("Nutrition"), 0, 'Sodium, Na') ,
            'max': np.append(df_max.column(column), [999999]*(len(df_min.column(column))-1)),
            'min': np.insert(df_min.column(column), 0, 0) 
            }

    return pd.DataFrame(data)


# Testings: 
dri(20, 'F')

                         Nutrition     max     min
0                       Sodium, Na    2300     0.0
1                           Energy    3100  2000.0
2                          Protein  999999    46.0
3             Fiber, total dietary  999999    28.0
4                      Folate, DFE  999999   400.0
5                      Calcium, Ca  999999  1000.0
6      Carbohydrate, by difference  999999   130.0
7                         Iron, Fe  999999    18.0
8                    Magnesium, Mg  999999   310.0
9                           Niacin  999999    14.0
10                   Phosphorus, P  999999   700.0
11                    Potassium, K  999999  4700.0
12                      Riboflavin  999999     1.1
13                         Thiamin  999999     1.1
14                  Vitamin A, RAE  999999   700.0
15                    Vitamin B-12  999999     2.4
16                     Vitamin B-6  999999     1.3
17  Vitamin C, total ascorbic acid  999999    75.0
18    Vitamin E (alpha-tocopherol)  999999    15.0
19       Vitamin K (phylloquinone)  999999    90.0
20                        Zinc, Zn  999999     8.0

In [57]:
# [A] Nutritional content of different foods

# Put an FDC ID HERE!
id =  [['chicken',2727569],['rice', 1999628],['pineapple',2346398]] 

def nutrition_table(id):
    # List of nutrient
    nutrient_df = pd.DataFrame({
                    'Nutrition': np.insert(df_min.column("Nutrition"), 0, 'Sodium, Na') ,
                    })
    
    for i in id:
        # Modifying data
        food_nutrient = fdc.nutrients(apikey,fdc_id=i[1])
        food_nutrient = food_nutrient.rename(index={"Energy (Atwater General Factors)": "Energy"})
        food_nutrient = food_nutrient.reset_index().rename(columns={'index': 'Nutrition','Quantity':i[0]}).drop("Units", axis=1)
        food_nutrient[food_nutrient.select_dtypes("number").columns] = food_nutrient.select_dtypes("number").clip(lower=0)
        
        
        nutrient_df = pd.merge(nutrient_df, food_nutrient, on='Nutrition', how='left')
        
    return nutrient_df.fillna(0)


# Testings: 
nutrition_table(id)

                         Nutrition    chicken        rice   pineapple
0                       Sodium, Na   48.07000    0.936300    0.000000
1                           Energy  126.90500   44.095000   60.111300
2                          Protein   21.40625    2.414375    0.460938
3             Fiber, total dietary    0.00000    4.166000    0.934600
4                      Folate, DFE    0.00000    0.000000    0.000000
5                      Calcium, Ca    6.89800    0.766300   12.500000
6      Carbohydrate, by difference    0.00000    8.170625   14.091463
7                         Iron, Fe    0.35350    0.144300    0.054000
8                    Magnesium, Mg   25.40000   14.060000   13.380000
9                           Niacin    0.00000    2.741000    0.227500
10                   Phosphorus, P  203.60000   75.820000    5.420000
11                    Potassium, K  332.50000  243.000000  137.100000
12                      Riboflavin    0.00000    0.216300    0.000000
13                         Thiamin    0.00000    0.001250    0.063750
14                  Vitamin A, RAE    0.00000    0.000000    0.000000
15                    Vitamin B-12    0.00000    0.000000    0.000000
16                     Vitamin B-6    0.00000    0.159300    0.110100
17  Vitamin C, total ascorbic acid    0.00000    0.000000   58.610000
18    Vitamin E (alpha-tocopherol)    0.00000    0.000000    0.000000
19       Vitamin K (phylloquinone)    0.00000    0.000000    0.000000
20                        Zinc, Zn    0.62450    0.764100    0.106700

In [58]:
# [A] Solution - Part A: Producing 'A' 'B'

# Producing A_ub using the nutrition table generate from the function above\n",
def A_ub_function(df_nutrient_table):
    A_ub = []
    for i in range(len(df_nutrient_table)):
        A_ub.append(list(df_nutrient_table.iloc[i][1:]))

    for i in range(len(A_ub)):
        negative_a_ub = []
        for j in range(len(A_ub[0])):
            negative_a_ub.append(-A_ub[i][j])
        A_ub.append(negative_a_ub)

    return A_ub


# Producing A_ub using the google sheet we manually input\n",
df_nutrition = Table.read_table('Food_Local.csv')

def A_ub_sheet(df_sheet):
    A_ub = []
    for i in range(len(df_sheet[0])):
        A_ub.append(list(df_sheet.row(i))[2:]) # [2:] as exlduing the first column of food and the second column of units

    for i in range(len(A_ub)):
        negative_a_ub = []
        for j in range(len(A_ub[0])):
            negative_a_ub.append(-A_ub[i][j])
        A_ub.append(negative_a_ub)
    return A_ub

# Producing b_ub with given age and gender
def b_ub_age_gender(age, gender):
    restrictions = dri(20, 'F')
    b_ub = list(restrictions["max"]) + list(-restrictions["min"])
    return b_ub


# Producing the list of cost, assuming the cost is on the first row
df_price = Table.read_table('Price_Local.csv')

def cost_sheet(df):
    return list(df.row(0))

# Testings:
# A_ub_function(nutrition_table(id))
# A_ub_sheet(df_nutrition)
# b_ub_age_gender(20, 'F')

In [59]:
# [A] Solution - Part B: Solving the Problem with 'linprog'
# Exploring Local food (local only)

# defining 'A'
A_ub = A_ub_sheet(df_nutrition)

# defining cost
c = cost_sheet(df_price)

# defining 'b'
b_ub = b_ub_age_gender(20, 'F')

# Defining food_list
food_list = list(df_nutrition.labels)[2:] #[2:] becasue to exclude the nutrient column and unit column

# Assumption: A_ub, the cost and the list of food have the same order
def minimum_cost(A_ub, b_ub, c, food_list):
    # Bound for the x
    bounds = []
    for i in range(len(A_ub[0])):
        bounds.append((0, None))
    
    # Solving the problem and showing it in dataframe
    solution = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=bounds)

    df = pd.DataFrame({'Food': food_list,
            'Quantity (100g)': solution.x})
    return df


minimum_cost(A_ub, b_ub, c, food_list)

                                         Food  Quantity (100g)
0                        Cabbage (green, raw)         0.958180
1                                       Mango         0.000000
2                                     Chicken         0.000000
3   Rice (white, long grain, unenriched, raw)         0.000000
4                                 Soybean Oil         1.122487
5         Bread (white, enriched, unbleached)         0.000000
6                         Onion (yellow, raw)         0.000000
7                                   Raw Sugar         0.000000
8                               Beans (Black)         1.779426
9                                   Fish/tuna         0.000000
10                                       Eggs         1.589737
11                                       Corn         0.000000
12                                    Cheese          0.734404
13   Beef(Bovine Meat) ; (80% lean, 20% fat)          0.000000
14                                    Cassava         0.000000
15                                  plantains         0.000000
16                                 maize/corn        10.783699
17                             sweet potatoes         0.000000
18                                       yams         0.121205
19                                   avocados         0.000000
20                                    papayas         0.000000
21                                    coconut         0.000000
22                                    oranges         0.000000
23                                       lime         0.000000
24                         shiitake mushrooms         0.000000

In [65]:
# Exploring Local and import 

df_nutrition_LI = Table.read_table('Food_Import_Local.csv')
df_price_LI = Table.read_table('Price_Import_Local.csv')

# defining 'A'
A_ub_LI = A_ub_sheet(df_nutrition_LI)

# defining cost
c_LI = cost_sheet(df_price_LI)

# defining 'b'
b_ub_LI = b_ub_age_gender(20, 'F')

# Defining food_list
food_list_LI = list(df_nutrition_LI.labels)[2:]

minimum_cost(A_ub_LI, b_ub_LI, c_LI, food_list_LI)

                                                 Food  Quantity (100g)
0                                Cabbage (green, raw)         0.000000
1                                               Mango         0.000000
2                                             Chicken         0.000000
3           Rice (white, long grain, unenriched, raw)         0.000000
4                                         Soybean Oil         1.080714
5                 Bread (white, enriched, unbleached)         0.000000
6                                 Onion (yellow, raw)         0.000000
7                                           Raw Sugar         0.000000
8                                       Beans (Black)         0.211583
9                                           Fish/tuna         0.000000
10                                               Eggs         0.000000
11                                               Corn         0.000000
12                                            Cheese          1.310191
13                                              Wheat         0.000000
14           Beef(Bovine Meat) ; (80% lean, 20% fat)          0.000000
15              Pig Meat (pork belly, with skin, raw)         0.000000
16                   Edible Offal (chicken liver raw)         0.000000
17                                  Fish Fillet (cod)         0.000000
18  Dried/Salted/Smoked/Brined Fish (Fish, cod, At...         0.000000
19                                            Cassava         0.000000
20                                          plantains         1.953792
21                                         maize/corn        11.894953
22                                     sweet potatoes         0.000000
23                                               yams         0.000000
24                                           avocados         0.000000
25                                            papayas         0.000000
26                                            coconut         0.000000
27                                            oranges         0.000000
28                                               lime         0.000000
29                                 shiitake mushrooms         0.000000
30                          Edible Offal (pork liver)         0.403457

In [66]:
# [B] What is total cost for population of interest? - Part A: Population Function

# Population function from project 1

def population_1year(year,sex,age,place):    
    if sex == 'F':
        gender = "FE"
    else:
        gender = "MA"

    lower_range = age
    while (lower_range % 5) != 0:
        lower_range -= 1
    
    upper_range = age 
    while ((upper_range-4) % 5) != 0:
        upper_range += 1

    if lower_range < 10:
        lower_str = "0" + str(lower_range)
    else:
        lower_str = str(lower_range)

    if upper_range < 10:
        upper_str = "0" + str(upper_range)
    else:
        upper_str = str(upper_range)
        
    data = "SP.POP." + lower_str + upper_str + "." + gender
    
    variable_labels = {data:"Population"}
    world = wbdata.get_dataframe(variable_labels, country=place, parse_dates=True)
    
    filtered = world[world.index.year == year]
    if filtered.empty:
        return 0
    return filtered.iloc[0]['Population'] / 5


#Getting the population by year, gender, age range and place.
#Coded based on population_1year function
def population(year,sex,age_range,place):
    lower_range = age_range[0]
    higher_range = age_range[1]
    population = 0
    
    while higher_range >= lower_range:
        population += population_1year(year,sex,lower_range,place)
        lower_range += 1

    return population
        
'''
Instruction for using the population function:
1. Year is limited to be between 1960 to 2024.
2. Type either 'F' or 'M' for gender.
3. See "wbdata.get_countries()"  for country code
4. About age range: 
    a. Type (lower range, upper range)
        i. It is inclusive, which mean the range (15,19) include the population for both age 15 and age 19.
    b. lower range has to be: 0 - 78
    c. upper range has to be: 1 - 79 
    d. Upper range has to be greater than lower range
'''

#Example:
print(population_1year(2021, 'F',19,'HTI'))
print(population(2021, 'F', (15,19), 'HTI'))
print(population(2021, 'F', (43,78), 'HTI'))

113653.0
568265.0
1213870.4

In [68]:
# [B] What is total cost for population of interest? - Part B: Calculating Total cost 

# Total cost of the population of one age and one gender in one country on input year
def total_cost(year, gender, age, country, cost, A_ub, food_list):
    b_ub = b_ub_age_gender(age, gender)
    df_food = minimum_cost(A_ub, b_ub, cost, food_list)
    return sum(list(df_food['Quantity (100g)'] * cost)) * population_1year(year, gender, age, country)

# Total cost of the population of the input country on input year
def total_cost_whole_country(year, country, cost, A_ub, food_list):

    # Getting total cost for one gender
    def total_cost_one_gender(gender):

        # Adding population for 80UP as my population does not include that
        if gender == 'F':
            g = 'FE'
        else: 
            g = 'MA'

        data = "SP.POP.80UP." + g
    
        variable_labels = {data:"Population"}
        world = wbdata.get_dataframe(variable_labels, country=country, parse_dates=True)  
        filtered = world[world.index.year == year]
        total = filtered.iloc[0]['Population']

        for i in range(79):
            total += total_cost(year, gender, i, country, cost, A_ub,food_list)
        return total
        
    df = pd.DataFrame({'Gender': ['Male','Female','Total'],
            'Cost': [total_cost_one_gender('M'), total_cost_one_gender('F'), total_cost_one_gender('M')+total_cost_one_gender('F')]})
    return df

In [69]:
# Total cost for local food only
total_cost_whole_country(2024, 'HTI', c, A_ub, food_list)

   Gender          Cost
0    Male  1.374006e+07
1  Female  1.399755e+07
2   Total  2.773761e+07

In [70]:
# Total cost for having both local and import food
total_cost_whole_country(2024, 'HTI', c_LI, A_ub_LI, food_list_LI)

   Gender          Cost
0    Male  1.469968e+07
1  Female  1.497403e+07
2   Total  2.967371e+07

In [71]:
# [C] Sensitivity of solution 

# Cost of one meal of the person with input age and input gender
def one_meal_cost(gender, age, cost, A_ub, food_list):
    b_ub = b_ub_age_gender(age, gender)
    df_food = minimum_cost(A_ub, b_ub, cost, food_list)
    return sum(list(df_food['Quantity (100g)'] * cost))

# Sensitivity 
# Assumption: A_ub, the cost and the list of food have the same order
def sensitivity(gender, age, cost, A_ub, food_list, food_with_price_change):

    index = food_list.index(food_with_price_change)
    
    percentage_change = [0, 5, 10, 50, 100, 200]
    b_ub = b_ub_age_gender(age, gender)
    df = {'Food': food_list + ['Total Price']}
    
    for i in percentage_change:
        new_cost = cost[:]
        new_cost[index] *= (1+(0.01*i))
        df_food = minimum_cost(A_ub, b_ub, new_cost, food_list)
        df[str(i)+"% change for " + food_with_price_change] = list(df_food['Quantity (100g)']) + [one_meal_cost(gender, age, new_cost, A_ub, food_list)]

    return pd.DataFrame(df)
        
sensitivity('F', 20, c , A_ub,food_list, 'Mango')

,Food,0% change for Mango,5% change for Mango,10% change for Mango,50% change for Mango,100% change for Mango,200% change for Mango
0,"Cabbage (green, raw)",0.958180,0.958180,0.958180,0.958180,0.958180,0.958180
1,Mango,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Chicken,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,"Rice (white, long grain, unenriched, raw)",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Soybean Oil,1.122487,1.122487,1.122487,1.122487,1.122487,1.122487
5,"Bread (white, enriched, unbleached)",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,"Onion (yellow, raw)",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,Raw Sugar,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,Beans (Black),1.779426,1.779426,1.779426,1.779426,1.779426,1.779426
9,Fish/tuna,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,Eggs,1.589737,1.589737,1.589737,1.589737,1.589737,1.589737
11,Corn,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,Cheese,0.734404,0.734404,0.734404,0.734404,0.734404,0.734404
13,"Beef(Bovine Meat) ; (80% lean, 20% fat)",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,Cassava,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,plantains,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,maize/corn,10.783699,10.783699,10.783699,10.783699,10.783699,10.783699
17,sweet potatoes,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,yams,0.121205,0.121205,0.121205,0.121205,0.121205,0.121205
19,avocados,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,papayas,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,coconut,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,oranges,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,lime,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,shiitake mushrooms,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,Total Price,2.367620,2.367620,2.367620,2.367620,2.367620,2.367620